FROM ubuntu:18.04

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    software-properties-common \
    build-essential \
    ca-certificates \
    curl \
    git \
    openssh-client \
    openssh-server \
    vim \
    wget \
    python3-dev \
    && ln -s -f /usr/bin/python3 /usr/bin/python \
    && ln -s /usr/local/bin/pip3 /usr/bin/pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# MXNet requires pip 19.3.1 due to being backwards compatible
# with python2
RUN cd /tmp && \
    curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py 'pip==19.1' && rm get-pip.py

RUN pip install --no-cache mxnet==1.6.0

# OpenSHH config for MPI communication
RUN mkdir -p /var/run/sshd && \
  sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

RUN rm -rf /root/.ssh/ && \
  mkdir -p /root/.ssh/ && \
  ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa && \
  cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys \
  && printf "Host *\n StrictHostKeyChecking no\n" >> /root/.ssh/config

COPY dist/sagemaker_mxnet_training-*.tar.gz /sagemaker_mxnet_training.tar.gz
RUN pip install --no-cache-dir /sagemaker_mxnet_training.tar.gz && \
    rm /sagemaker_mxnet_training.tar.gz

ENV SAGEMAKER_TRAINING_MODULE=sagemaker_mxnet_container.training:main

WORKDIR /
