# Use local version of image built from Dockerfile.cpu in /docker/$version/base directory
FROM mxnet-base:0.12.1-cpu-py2

RUN pip2 install --no-cache \
    numpy==1.13.3 requests==2.18.4 graphviz==0.8.1 boto3==1.5.2 \
    six==1.11.0 gevent==1.2.2 gunicorn==19.7.1 flask==0.11 Jinja2==2.9

ENV PYTHONPATH="/opt/amazon/lib/python2.7/site-packages/"
ENTRYPOINT ["python2", "/opt/amazon/bin/entry.py"]
