# Use local version of image built from Dockerfile.gpu in /docker/$version/base directory
FROM mxnet-base:0.12.1-gpu-py2
ARG mxnet_support_tar=sagemaker_mxnet_container-1.0.0.tar.gz

RUN pip2 install --no-cache \
    numpy==1.13.3

COPY $mxnet_support_tar .

RUN pip2 install $mxnet_support_tar

RUN rm $mxnet_support_tar

# Entrypoint script comes from sagemaker_container_support
ENTRYPOINT ["/usr/bin/python2", "/usr/local/bin/entry.py"]
