# Use local version of image built from Dockerfile.cpu in /docker/$version/base directory
FROM mxnet-base:1.0.0-gpu-py2

ENV PYTHONPATH="/opt/amazon/lib/python2.7/site-packages/"
ENTRYPOINT ["python2", "/opt/amazon/bin/entry.py"]
